In [ ]:
Section A: Data Structures & Control Structures
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [17]:

lst = [1, 2, 3, 4, 5]

# append
lst.append(6)
print("Append:", lst)

# extend
lst.extend([7, 8])
print("Extend:", lst)

# insert
lst.insert(2, 99)
print("Insert:", lst)

# remove
lst.remove(99)
print("Remove:", lst)

# pop
lst.pop()
print("Pop:", lst)

# index
print("Index of 3:", lst.index(3))

# count
print("Count of 2:", lst.count(2))

# sort
lst.sort()
print("Sort:", lst)

# reverse
lst.reverse()
print("Reverse:", lst)

# clear
lst.clear()
print("Clear:", lst)
   

Append: [1, 2, 3, 4, 5, 6]
Extend: [1, 2, 3, 4, 5, 6, 7, 8]
Insert: [1, 2, 99, 3, 4, 5, 6, 7, 8]
Remove: [1, 2, 3, 4, 5, 6, 7, 8]
Pop: [1, 2, 3, 4, 5, 6, 7]
Index of 3: 2
Count of 2: 1
Sort: [1, 2, 3, 4, 5, 6, 7]
Reverse: [7, 6, 5, 4, 3, 2, 1]
Clear: []


In [ ]:
2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [6]:
students = ("Asha", "Ravi", "Kiran")
print("\nTuple:", students)

try:
    students[1] = "Rahul"   # This will cause error
except TypeError as e:
    print("Error:", e)
    print("Tuples are immutable (cannot be changed)")


Tuple: ('Asha', 'Ravi', 'Kiran')
Error: 'tuple' object does not support item assignment
Tuples are immutable (cannot be changed)


In [ ]:
3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [7]:
s = {1, 2, 2, 3, 4, 4}
print("Set:", s)
print("Explanation: Duplicates are removed automatically.")

Set: {1, 2, 3, 4}
Explanation: Duplicates are removed automatically.


In [ ]:
A set in Python automatically removes duplicate values because it stores only unique elements. Even though duplicates (2 and 4) are given, the output will contain each number only once. Also, sets are unordered, so the elements may not appear in the same order as entered.

In [ ]:
4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [8]:
person = {'name': 'John', 'age': 25, 'city': 'Delhi'}

person['age'] = 30
person['email'] = 'john@example.com'

print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'John', 'age': 30, 'city': 'Delhi', 'email': 'john@example.com'}


In [ ]:
Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [9]:
age = int(input("Enter age: "))

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter age:  23


Eligible to vote


In [ ]:
6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [10]:
marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")


Enter marks:  84


Grade: B


In [ ]:
7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative

In [11]:
num = int(input("Enter a number: "))

if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Enter a number:  15


Positive but Odd


In [ ]:
Section B: 
   Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [12]:
import numpy as np
import pandas as pd

# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2D array (2x3)
arr2 = np.arange(10, 70, 10).reshape(2, 3)
print("2D Array:\n", arr2)



Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [ ]:
9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [13]:

rand_arr = np.random.randint(0, 100, (4, 4))
print("Random Array:\n", rand_arr)

Random Array:
 [[35  4  0  6]
 [86 55 84 61]
 [62 39 73 56]
 [83  3 75 37]]


In [ ]:
10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [14]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr3, columns=['A', 'B', 'C'])
print("DataFrame:\n", df)

DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [ ]:
Section C:
Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [16]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'Age': [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    'City': ['BLR', 'MYS', 'HYD', 'DEL', 'CHE', 'PUN', 'MUM', 'KOL', 'GOA', 'BLR'],
    'Salary': [50000, 60000, None, 55000, 62000, None, 58000, 61000, 59000, 60000]
}

df = pd.DataFrame(data)

print("INFO:")
df.info()

print("\nDESCRIBE:")
print(df.describe())


print("\nSelected Columns:")
print(df[['Name', 'City']])

df = df.drop(columns=['City'])
print("\nAfter Dropping City:")
print(df)


df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print("\nAfter Filling Missing Values:")
print(df)

df = df.drop_duplicates()
print("\nAfter Removing Duplicates:")
print(df)


INFO:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

DESCRIBE:
            Age        Salary
count  10.00000      8.000000
mean   25.50000  58125.000000
std     3.02765   3907.410542
min    21.00000  50000.000000
25%    23.25000  57250.000000
50%    25.50000  59500.000000
75%    27.75000  60250.000000
max    30.00000  62000.000000

Selected Columns:
  Name City
0    A  BLR
1    B  MYS
2    C  HYD
3    D  DEL
4    E  CHE
5    F  PUN
6    G  MUM
7    H  KOL
8    I  GOA
9    J  BLR

After Dropping City:
  Name  Age   Salary
0    A   21  50000.0
1    B   22  60000.0
2    C   23      NaN
3    D   24  55000.0
4    E   25  62000.0
5    F   26      NaN
6  

C:\Users\SS\AppData\Local\Temp\ipykernel_30616\3553145626.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
